import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Profile": "Profile",
          "Language": "Language",
          "Error in login": "Error in login",
          "Goverenrate": "Goverenrate",
          "License unit": "License unit",
          "Need check": "Need check",
          "Installment": "Installment",
          "Visit time": "Visit time",
          "Save": "Save",
        },
        'ar': {
          "Profile": "الصفحة الشخصية",
          "Language": "اللغة",
          "Login": "تسجيل الدخول",
          "Welcome Back": "مرحبا مجددا",
          "Forgot Password?": "نسيت كلمة السر ؟",
          "Error": "حطأ",
          "Login as a guest": "دخول كزائر",
          "Error in login": "خطأ في عملية الدخول",
          "Goverenrate": "المحافظة",
          "License unit": "وحدة الترخيص",
          "Need check": "فحص فني",
          "Installment": "التقسيط",
          "Visit time": "وقت الزيارة",
          "Save": "حفظ",
          "Welcome": "مرحبا",
          "Renew driving license": "تجديد رخصة القيادة",
          "Driving license": "رخصة القيادة ",
          "Car license": "رخصة السيارة",
          "My requests": "طلباتي",
          "Logout": "تسجيل الخروج",
          "Delete Account": "حذف حسابي",
          "Car License": "رخصة السيارة",
          "1 Year": "سنة",
          "2 Year": "سنتان",
          "3 Year": "ثلاث سنوات",
          "Renewale duration": "فترة التجديد",
          "National ID": "البطاقة الشخصية",
          "License Image": "صورة الرخصة",
          "Notes": "ملاحظات",
          "New Car": "سيارة جديدة",
          "Settings": "الإعدادات",
          "Open settings to allow access":
              "الذهاب إلي الإعدادات لتمكين التطبيق من صلاحيات الوصول للصور",
          "Photo access required": "يتطلب التطبيق الإذن للوصول إلي الصور",
          "Add an image": "أضف صورة",
          "Driver License": "رخصة القيادة",
          "Error in forget password": "خطأ في استرجاع الرقم السري",
          "Done": "تم",
          "Registeration": 'إنشاء حساب',
          "Name": "الإسم",
          "Email": "البريد الإليكتروني",
          "Phone Number": "رقم الهاتف",
          "Password": "الرقم السري",
          "Confirm Password": "تأكيد الرقم السري",
          "Error in signUp": "خطأ في إنشاء الحساب",
          "Sign Up": "إنشاء الحساب",
          "Retry": "أعد المحاولة",
          "Rating is done": "تم التقييم بنحاح",
          "Error in rating": "خطأ في التقييم"
        },
      };
}
